"""add_execution_time_to_work_records

Revision ID: 6cd36b2244cd
Revises: a49a795de448
Create Date: 2025-08-22 15:30:14.611968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd36b2244cd'
down_revision: Union[str, Sequence[str], None] = 'a49a795de448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_comments', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    
    # 先新增可為空的欄位
    op.add_column('work_records', sa.Column('execution_time_minutes', sa.Integer(), nullable=True))
    
    # 更新現有記錄的預設值為 0 (0 分鐘)
    op.execute("UPDATE work_records SET execution_time_minutes = 0 WHERE execution_time_minutes IS NULL")
    
    # 再將欄位設為 NOT NULL
    op.alter_column('work_records', 'execution_time_minutes', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_records', 'execution_time_minutes')
    op.alter_column('review_comments', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
