"""add_multi_supervisor_approval_system

Revision ID: a49a795de448
Revises: c5efbfd998f2
Create Date: 2025-08-20 09:20:03.266229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49a795de448'
down_revision: Union[str, Sequence[str], None] = 'c5efbfd998f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', name='approvalstatus'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'supervisor_id', name='unique_report_supervisor_approval')
    )
    op.create_index(op.f('ix_report_approvals_id'), 'report_approvals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_approvals_id'), table_name='report_approvals')
    op.drop_table('report_approvals')
    # ### end Alembic commands ###
