"""restructure employee department relationship for company A only

Revision ID: c5efbfd998f2
Revises: 06c938910d91
Create Date: 2025-08-18 15:18:09.094536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5efbfd998f2'
down_revision: Union[str, Sequence[str], None] = '06c938910d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_departments')
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('employees', 'company_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=False)
    op.create_index(op.f('ix_employees_company_code'), 'employees', ['company_code'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_code'), table_name='employees')
    op.alter_column('employees', 'company_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('employees', 'department_id')
    op.create_table('employee_departments',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('employee_departments_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_departments_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'department_id', name=op.f('employee_departments_pkey'))
    )
    # ### end Alembic commands ###
