"""Add comprehensive employee relationship tables

Revision ID: cf5da576e8fe
Revises: employee_supervisor_m2m
Create Date: 2025-08-18 11:26:52.079712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5da576e8fe'
down_revision: Union[str, Sequence[str], None] = 'employee_supervisor_m2m'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_no', sa.String(length=50), nullable=False),
    sa.Column('dept_name', sa.String(length=200), nullable=False),
    sa.Column('dept_abbr', sa.String(length=100), nullable=True),
    sa.Column('group_dept_no', sa.String(length=50), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_dept_name'), 'departments', ['dept_name'], unique=False)
    op.create_index(op.f('ix_departments_dept_no'), 'departments', ['dept_no'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('employee_department_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_department_history_id'), 'employee_department_history', ['id'], unique=False)
    op.create_table('employee_position_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('dclass', sa.String(length=50), nullable=True),
    sa.Column('xlevel', sa.Numeric(), nullable=True),
    sa.Column('admin_rank', sa.String(length=50), nullable=True),
    sa.Column('group_emp_no', sa.String(length=50), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_position_history_id'), 'employee_position_history', ['id'], unique=False)
    op.create_table('employee_supervisor_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_supervisor_history_id'), 'employee_supervisor_history', ['id'], unique=False)
    op.create_foreign_key(None, 'daily_reports', 'employees', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_employee_supervisors_employee_id'), table_name='employee_supervisors')
    op.drop_index(op.f('ix_employee_supervisors_supervisor_id'), table_name='employee_supervisors')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'work_records', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_records', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_index(op.f('ix_employee_supervisors_supervisor_id'), 'employee_supervisors', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_employee_supervisors_employee_id'), 'employee_supervisors', ['employee_id'], unique=False)
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_index(op.f('ix_employee_supervisor_history_id'), table_name='employee_supervisor_history')
    op.drop_table('employee_supervisor_history')
    op.drop_index(op.f('ix_employee_position_history_id'), table_name='employee_position_history')
    op.drop_table('employee_position_history')
    op.drop_index(op.f('ix_employee_department_history_id'), table_name='employee_department_history')
    op.drop_table('employee_department_history')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_dept_no'), table_name='departments')
    op.drop_index(op.f('ix_departments_dept_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
