"""add department relationship to projects

Revision ID: e7ed5066efeb
Revises: cf5da576e8fe
Create Date: 2025-08-18 14:35:58.206631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ed5066efeb'
down_revision: Union[str, Sequence[str], None] = 'cf5da576e8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_projects_department', 'projects', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_department', 'projects', type_='foreignkey')
    op.drop_column('projects', 'department_id')
    # ### end Alembic commands ###
